// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'long AmplifyingStack.RunDirect(long input, IEnumerable<int> phaseSettingSequence)' passes a literal string as parameter 'message' of a call to 'ArgumentException.ArgumentException(string? message)'. Retrieve the following string(s) from a resource table instead: \"Phase setting sequence is invalid\".", Justification = "<Pending>", Scope = "member", Target = "~M:DaySeven.Model.AmplifyingStack.RunDirect(System.Int64,System.Collections.Generic.IEnumerable{System.Int32})~System.Int64")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'long AmplifyingStack.RunLooping(long input, IEnumerable<int> phaseSettingSequence)' passes a literal string as parameter 'message' of a call to 'ArgumentException.ArgumentException(string? message)'. Retrieve the following string(s) from a resource table instead: \"Phase setting sequence is invalid\".", Justification = "<Pending>", Scope = "member", Target = "~M:DaySeven.Model.AmplifyingStack.RunLooping(System.Int64,System.Collections.Generic.IEnumerable{System.Int32})~System.Int64")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member WriteProgramInput does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "<Pending>", Scope = "member", Target = "~M:DaySeven.Model.AmplifyingStack.WriteProgramInput(System.Int32,System.Int64,System.Int32[])~System.Collections.Generic.IEnumerable{System.Int64}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1062:In externally visible method 'IEnumerable<long> AmplifyingStack.WriteProgramInput(int ampliId, long input, int[] phaseSettings)', validate parameter 'phaseSettings' is non-null before using it. If appropriate, throw an ArgumentNullException when the argument is null or add a Code Contract precondition asserting non-null argument.", Justification = "<Pending>", Scope = "member", Target = "~M:DaySeven.Model.AmplifyingStack.WriteProgramInput(System.Int32,System.Int64,System.Int32[])~System.Collections.Generic.IEnumerable{System.Int64}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'void Program.Main(string[] args)' passes a literal string as parameter 'message' of a call to 'Exception.Exception(string? message)'. Retrieve the following string(s) from a resource table instead: \"File is empty.\".", Justification = "<Pending>", Scope = "member", Target = "~M:DaySeven.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter args of method Main is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:DaySeven.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'Main' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:DaySeven.Program.Main(System.String[])")]