// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2208:Call the ArgumentNullException constructor that contains a message and/or paramName parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:DayTen.Model.Asteroid.GetRangeX(DayTen.Model.ILocation,DayTen.Model.ILocation)~System.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2208:Call the ArgumentNullException constructor that contains a message and/or paramName parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:DayTen.Model.Asteroid.GetRangeY(DayTen.Model.ILocation,DayTen.Model.ILocation)~System.")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'bool Asteroid.HasDirectLineOfSight(Map map, Asteroid targetAsteroid)' passes a literal string as parameter 'message' of a call to 'ArgumentException.ArgumentException(string? message)'. Retrieve the following string(s) from a resource table instead: \"One or both asteroids do not belong to the map.\".", Justification = "<Pending>", Scope = "member", Target = "~M:DayTen.Model.Asteroid.HasDirectLineOfSight(DayTen.Model.Map,DayTen.Model.Asteroid)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2208:Call the ArgumentNullException constructor that contains a message and/or paramName parameter.", Justification = "<Pending>", Scope = "member", Target = "~M:DayTen.Model.Asteroid.IsAlignedWith(DayTen.Model.ILocation,DayTen.Model.ILocation)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1720:Identifier 'obj' contains type name", Justification = "<Pending>", Scope = "member", Target = "~M:DayTen.Model.ILocation.Equals(System.Object)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1303:Method 'void Program.Main(string[] args)' passes a literal string as parameter 'message' of a call to 'FileNotFoundException.FileNotFoundException(string? message)'. Retrieve the following string(s) from a resource table instead: \"path\".", Justification = "<Pending>", Scope = "member", Target = "~M:DayTen.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter args of method Main is never used. Remove the parameter or use it in the method body.", Justification = "<Pending>", Scope = "member", Target = "~M:DayTen.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1031:Modify 'Main' to catch a more specific allowed exception type, or rethrow the exception.", Justification = "<Pending>", Scope = "member", Target = "~M:DayTen.Program.Main(System.String[])")]